
# Site settings
title: Shiwu Liao
email: liaoshiwu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. student at Huazhong Univ. of Sci. and Tech.
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
logo: "/assets/img/logo.png"



# baidu analytics
ba:
  uuid: 3252078aa9ce5134316b0920c6093121

# google analytics
ga:
  id: UA-83437743-1




# Build settings
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

gems:
  - jekyll-gist
  - jekyll-paginate